language: node_js
node_js:
  - '8.9.1'

cache:
  directories:
    - "node_modules"
    
sudo: required
addons:
    chrome: stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
 
install:
 - npm set progress=false
 - npm install
 
script:
 -  npm run test
 - # npm run electron:linux
 - # npm run build:prod
 

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "release/SDD*.*"
  #file: "dist/**/*"
  skip_cleanup: true
  on:
    tags: true
